/*
************************************************************************
Class Name         : CalendarEventDetails
Created Date       : Feb 10, 2024
@description       : This class is used to deserialize calendar event response
@author            : Soham Datta

Modification Log   :
Ver   Date         Author                               Modification
1.0   10-02-2024   Soham Datta                         Initial Version
*************************************************************************
*/

public class CalendarEventDetails{
    
	public String kind;	
	public String status;	
	public String htmlLink;	
	public String created;	
	public String updated;	
	public String summary;	

}