/*
************************************************************************
Class Name         : ConstantClass
Created Date       : Feb 5, 2024
@description       : This is constant class
@author            : Soham Datta

Modification Log   :
Ver   Date         Author                               Modification
1.0   04-02-2024   Soham Datta                         Initial Version
*************************************************************************
*/

public class ConstantClass {
    
    public static final String METHOD_GET = 'GET';
    public static final String METHOD_POST = 'POST';
    public static final String METHOD_DELETE = 'DELETE';
    public static final String METHOD_PUT = 'PUT';

    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String CONTENT_TYPE_VALUE = 'application/json';
    public static final String ACCEPT = 'Accept';
    public static final String LINKEDIN_VERSION = 'LinkedIn-Version';

    public static final String AUTHORIZATION = 'Authorization';
    public static final String BEARER = 'Bearer';

}