/*
************************************************************************
Class Name         : CustomException
Created Date       : Feb 5, 2024
@description       : This is custom exception class
@author            : Soham Datta

Modification Log   :
Ver   Date         Author                               Modification
1.0   04-02-2024   Soham Datta                         Initial Version
*************************************************************************
*/

public class CustomException extends Exception {
    
}