/*
************************************************************************
Class Name         : LinkedinProfileDetails
Created Date       : Feb 13, 2024
@description       : This class is used to deserialize Linkedin profile information
@author            : Soham Datta

Modification Log   :
Ver   Date         Author                               Modification
1.0   13-02-2024   Soham Datta                         Initial Version
*************************************************************************
*/
public class LinkedinProfileDetails {
    
  public String localizedLastName;	
	public String vanityName;	
	public String localizedHeadline;	
	public String id;	
	public String localizedFirstName;

}