/*
************************************************************************
Class Name         : GoogleToken
Created Date       : Feb 10, 2024
@description       : This class is used to deserialize Google token response
@author            : Soham Datta

Modification Log   :
Ver   Date         Author                               Modification
1.0   10-02-2024   Soham Datta                         Initial Version
*************************************************************************
*/

public class LinkedinToken {
    
    public String access_token;  
    public Integer expires_in;  
    public String token_type;  
    public String scope;  
    public String refresh_token; 
    
}